INSERT INTO roles (id, name) VALUES (1, 'ADMIN');
INSERT INTO roles (id, name) VALUES (2, 'USER');
INSERT INTO users (id, name, lastname, username, email, password) VALUES (1, 'Angel', 'Hincho', 'ahincho', 'ahincho@unsa.edu.pe', '$2a$10$1NZNQBOfL35xCtHn7l5k7uN82zoP8I6DObau06CnKTSmuPYA0uFtq');
INSERT INTO users_roles (role_id, user_id) VALUES (1, 1);
INSERT INTO categories (id, name) VALUES (1, 'Benzodiazepines');
INSERT INTO categories (id, name) VALUES (2, 'Serotonin Inhibitors');
INSERT INTO categories (id, name) VALUES (3, 'Tricyclic Antidepressants');
INSERT INTO categories (id, name) VALUES (4, 'Atypical Antidepressants');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (1, 'Lorazepam', 1, 'The recommended dose range is 2 to 6 mg/day, but the dose may vary from 1 to 10 mg/day', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (2, 'Clonazepam', 1, 'The drops should be mixed with water and administered with a spoon. It should never be administered directly from the container', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (3, 'Sertralina', 2, 'Usually the dose is 50 mg to 200 mg. Only your provider can determine the right dose for you', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (4, 'Citalopram', 2, 'Citalopram is an antidepressant medication. It is approved for the treatment of major depressive disorder (MDD)', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (5, 'Prazepam', 1, 'Store the medication in a closed container at room temperature and away from heat, moisture, and direct light', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (6, 'Flurazepam', 1, 'It is a medicine that has been used to treat insomnia (difficulty falling asleep or staying asleep)', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (7, 'Triazolam', 1, 'This medicinal product contains 72 mg lactose and 0.15 mg sodium benzoate (E-211) in each tablet', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (8, 'Clordiazepoxida', 1, 'It is used to relieve anxiety by reducing abnormal electrical activity in the brain', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (9, 'Halazepam', 1, 'Symptomatic relief of anxiety. Adjuvant in pathological states of anxiety, tension and apprehension', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (10, 'Temazepam', 1, 'It is a hypnotic drug, active orally. It is used for the short-term treatment of insomnia', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (11, 'Oxazepam', 1, 'It is used to relieve anxiety caused by alcohol withdrawal by slowing down brain activity', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (12, 'Clorazepato', 1, 'Which has anxiolytic, hypnotic, anticonvulsant, sedative, muscle relaxant and amnestic effect', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (13, 'Diazepam', 1, 'It is used to treat anxiety and as a muscle relaxant, among other uses', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (14, 'Alprazolam', 1, 'It is used to treat states of anxiety, agoraphobia, panic attacks and intense stress', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (15, 'Fluvoxamina', 2, 'It has low affinity for adrenergic, histaminergic, cholinergic, dopaminergic and serotonergic receptors', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (16, 'Paroxetina', 2, 'It is a potent inhibitor of neuronal reuptake of serotonin, has effects on norepinephrine and dopamine', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (17, 'Fluoxetina', 2, 'It is used to treat alcoholism, borderline personality disorder, post-traumatic stress disorder', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (18, 'Escitalopram', 2, 'It is used to treat depression in adults and children and adolescents 12 years of age and older', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (19, 'Imipramina', 3, 'It is a drug capable of raising noradrenaline and serotonin concentrations in the brain', 'abc');
INSERT INTO medicines (id, name, category_id, description, image_url) VALUES (20, 'Nortriptilina', 3, 'This helps improve mood and may reduce a person’s craving for nicotine', 'abc');